name:  Hellow world workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on:  ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hellow, Github Actions"
